### PR TITLE
add finalize subroutine for stochastic physics

### PR DESCRIPTION
**Pull request by pjpegion**
This a new feature to add a finalize subroutine to deallocate array at the end of a run.  Associated with PRs
https://github.com/NOAA-EMC/fv3atm/pull/199 and 
https://github.com/ufs-community/ufs-weather-model/issues/278

### CODE REVIEW

**Review by lisa-bengtsson — APPROVED** [review]
Looks good to me.

**Comment by HenryWinterbottom-NOAA** [comment]
I would strongly suggest adding `if-def `type statements to this PR. For example, instead of:

`deallocate(variable)`

do:

`if(allocated(variable)) deallocate(variable)`

This better protects the code from possible and difficult to chase segmentation faults in the future -- at least based on my experience.

**Comment by pjpegion** [comment]
@HenryWinterbottom-NOAA good point,  I thought about doing it, but was just lazy.

**Comment by HenryWinterbottom-NOAA** [comment]
@pjpegion If you are planning to do it, just send me a note (or submit a new PR) and I am happy to approve.

**Comment by pjpegion** [comment]
@HenryWinterbottom-NOAA I added the if (allocated()) conditionals

**Review by HenryWinterbottom-NOAA — APPROVED** [review]
Thank you @pjpegion.

Approved.

**Review by climbfuji — COMMENTED** [review]
The PR looks okay; there are several places where a comment line
```
! Copy blocked data into contiguous arrays; no need to copy weights in (intent(out))
```
was moved around to places where it doesn't belong. I recommend removing or changing them, but certainly not a show stopper.

I am currently creating new baselines on cheyenne.intel, cheyenne.gnu and gaea.intel. The new baseline date tag will be 20201127, please update `RTPWD` in `rt.sh` accordingly.

**Comment by pjpegion** [comment]
Looks like the changes you are suggesting are for the fv3atm PR.

**Comment by climbfuji** [comment]
> Looks like the changes you are suggesting are for the fv3atm PR.

Yes, sorry.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
